# Generated by Django 2.1.2 on 2019-02-07 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinics', '0002_auto_20190206_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic', models.ManyToManyField(to='Clinics.Service')),
                ('Patient', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
