# Generated by Django 2.1.2 on 2019-02-14 00:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('getter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='defaultPatient.jpg', upload_to='     patient_profile_pics'),
        ),
    ]
