# Generated by Django 2.1.2 on 2019-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20190215_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='static/patient_profile_pics/defaultPatient.jpg', upload_to='     patient_profile_pics'),
        ),
    ]
