# Generated by Django 2.1.2 on 2019-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20190215_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='defaultPatient.jpg', upload_to='patient_profile_pics'),
        ),
    ]
