# Generated by Django 2.1.2 on 2019-02-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_auto_20190206_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
