# Generated by Django 2.1.2 on 2019-02-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_auto_20190207_2254'),
        ('Staff', '0008_auto_20190207_2311'),
    ]

    operations = [
    ]
