# Generated by Django 2.1.2 on 2019-02-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_merge_20190208_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=300, null=True, upload_to='profile_pics', width_field=300),
        ),
    ]
