# Generated by Django 2.1.2 on 2019-02-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0012_auto_20190213_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
