# Generated by Django 2.1.2 on 2019-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='doctor',
            new_name='doctors',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='appointments',
            new_name='no_appointments',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
