# Generated by Django 2.1.2 on 2019-02-08 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_merge_20190208_0325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clinics', '0002_auto_20190206_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='no_appointments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clinics.Service'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.Doctor'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
