# Generated by Django 2.1.2 on 2019-02-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0003_auto_20190208_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Time',
            field=models.TimeField(),
        ),
    ]
