# Generated by Django 2.1.2 on 2019-02-08 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0004_auto_20190208_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='DateOfBook',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
