# Generated by Django 2.1.2 on 2019-02-08 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0005_reservation_dateofbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='DateOfBook101',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
