# Generated by Django 2.1.2 on 2019-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0007_remove_reservation_dateofbook101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='DateOfBook101',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
