# Generated by Django 2.1.2 on 2019-02-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0009_auto_20190208_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='DateOfBook101',
        ),
    ]
