# Generated by Django 2.1.2 on 2019-02-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clinics', '0010_remove_reservation_dateofbook101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Booker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Staff.Doctor'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Patient',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
