# Generated by Django 2.1.2 on 2019-02-11 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0012_auto_20190211_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Booker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
