# Generated by Django 2.1.2 on 2019-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0013_auto_20190212_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Slots',
            field=models.TimeField(choices=[('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30')], default=None),
            preserve_default=False,
        ),
    ]
