# Generated by Django 2.1.2 on 2019-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0015_auto_20190212_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='timeSlots',
            new_name='timeSlotss',
        ),
    ]
