# Generated by Django 2.1.2 on 2019-02-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0016_auto_20190212_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeSlotss',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clinics.TimeSlots'),
        ),
        migrations.AlterField(
            model_name='service',
            name='timeSlots',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clinics.TimeSlots'),
        ),
    ]
