# Generated by Django 2.1.2 on 2019-02-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0018_auto_20190212_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timeSlots',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='OpenSlots',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clinics.TimeSlots'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='t_id',
            field=models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
