# Generated by Django 2.1.2 on 2019-02-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0020_auto_20190212_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Time',
        ),
    ]
