# Generated by Django 2.1.2 on 2019-02-12 15:35

import Clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0021_remove_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='OpenSlots',
            field=models.DateTimeField(),
        ),
    ]
