# Generated by Django 2.1.2 on 2019-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0023_auto_20190212_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='name',
            field=models.CharField(default=models.DateTimeField(), max_length=50),
        ),
    ]
