# Generated by Django 2.1.2 on 2019-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0025_auto_20190212_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='timeSlots',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='OpenSlots',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
    ]
