# Generated by Django 2.1.2 on 2019-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0026_auto_20190212_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
