# Generated by Django 2.1.2 on 2019-02-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0027_reservation_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='OpenSlots',
            new_name='Time',
        ),
    ]
