# Generated by Django 2.1.2 on 2019-02-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0029_auto_20190213_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Day',
        ),
    ]
