# Generated by Django 2.1.2 on 2019-02-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0030_remove_reservation_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
