# Generated by Django 2.1.2 on 2019-02-13 18:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0031_reservation_day'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('rManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
