# Generated by Django 2.1.2 on 2019-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0032_auto_20190213_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
