# Generated by Django 2.1.2 on 2019-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0033_reservation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
