# Generated by Django 2.1.2 on 2019-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0034_auto_20190214_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default2.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
