# Generated by Django 2.1.5 on 2019-02-10 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultPatient.jpg', upload_to='patient_profile_pics')),
                ('Age', models.PositiveSmallIntegerField()),
                ('Blood_Type', models.CharField(choices=[('O Positive', 'O+'), ('O Negative', 'O-'), ('A Positive', 'A+'), ('A Negative', 'A-'), ('B Positive', 'B+'), ('B Negative', 'B-'), ('AB Positive', 'AB+'), ('AB Negative', 'AB-')], default='A Positive', max_length=11)),
                ('Weight', models.PositiveSmallIntegerField()),
                ('Height', models.PositiveSmallIntegerField()),
                ('Emergency_Contact', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
